In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv ('./german.csv',sep=',')
col = df.columns
print(col,'\n')
print('length,index:',df.shape,'\n')
# print(df.index,type(col[1]))
print(df.info(),'\n')

Index(['ID', 'checking_status', 'duration', 'credit_history', 'purpose',
       'credit_amount', 'savings_status', 'employment',
       'installment_commitment', 'personal_status', 'other_parties',
       'residence_since', 'property_magnitude', 'age', 'other_payment_plans',
       'housing', 'existing_credits', 'job', 'num_dependents', 'own_telephone',
       'foreign_worker', 'class'],
      dtype='object')

length,index: (1000, 22)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 22 columns):
ID                        1000 non-null int64
checking_status           1000 non-null object
duration                  996 non-null float64
credit_history            1000 non-null object
purpose                   997 non-null object
credit_amount             1000 non-null int64
savings_status            1000 non-null object
employment                1000 non-null object
installment_commitment    1000 non-null int64
personal_status           1000 non-null object
other_parties             1000 non-null object
residence_since           1000 non-null int64
property_magnitude        1000 non-null object
age                       1000 non-null int64
other_payment_plans       1000 non-null object
housing                   1000 non-null object
existing_credits          1000 non-null int64
job                       1000 non-null object
num_dependents            996 non-null float64
own_telephone             1000 non-null object
foreign_worker            1000 non-null object
class                     1000 non-null int64
dtypes: float64(2), int64(7), object(13)
memory usage: 172.0+ KB
None

In [3]:
print(df)

       ID checking_status  duration credit_history purpose  credit_amount  \
0       1             A11       6.0            A34     A43           1169
1       2             A12      48.0            A32     A43           5951
2       3             A14      12.0            A34       X           2096
3       4             A11      42.0            A32     NaN           7882
4       5             A11      24.0            A33     A40           4870
5       6             A14       NaN            A32       X           9055
6       7             A14      24.0            A32     A42           2835
7       8             A12      36.0            A32     A41           6948
8       9             A14      12.0            A32     A43           3059
9      10             A12      30.0            A34     NaN           5234
10     11             A12      12.0            A32     A40           1295
11     12             A11       NaN            A32     A49           4308
12     13             A12      12.0            A32     A43           1567
13     14             A11      24.0            A34     A40           1199
14     15             A11       NaN            A32     A40           1403
15     16             A11      24.0            A32     NaN           1282
16     17             A14       NaN            A34     A43           2424
17     18             A11      30.0            A30     A49           8072
18     19             A12      24.0            A32     A41          12579
19     20             A14      24.0            A32     A43           3430
20     21             A14       9.0            A34     A40           2134
21     22             A11       6.0            A32     A43           2647
22     23             A11      10.0            A34     A40           2241
23     24             A12      12.0            A34     A41           1804
24     25             A14      10.0            A34     A42           2069
25     26             A11       6.0            A32     A42           1374
26     27             A14       6.0            A30     A43            426
27     28             A13      12.0            A31     A43            409
28     29             A12       7.0            A32     A43           2415
29     30             A11      60.0            A33     A49           6836
..    ...             ...       ...            ...     ...            ...
970   971             A12      15.0            A32     A45           1514
971   972             A14      24.0            A32     A40           7393
972   973             A11      24.0            A31     A40           1193
973   974             A11      60.0            A32     A49           7297
974   975             A14      30.0            A34     A43           2831
975   976             A13      24.0            A32     A43           1258
976   977             A12       6.0            A32     A43            753
977   978             A12      18.0            A33     A49           2427
978   979             A14      24.0            A33     A40           2538
979   980             A12      15.0            A31     A40           1264
980   981             A12      30.0            A34     A42           8386
981   982             A14      48.0            A32     A49           4844
982   983             A13      21.0            A32     A40           2923
983   984             A11      36.0            A32     A41           8229
984   985             A14      24.0            A34     A42           2028
985   986             A11      15.0            A34     A42           1433
986   987             A13      42.0            A30     A49           6289
987   988             A14      13.0            A32     A43           1409
988   989             A11      24.0            A32     A41           6579
989   990             A12      24.0            A34     A43           1743
990   991             A14      12.0            A34     A46           3565
991   992             A14      15.0            A31     A43           1569
992   993             A11      18.0            A32     A43           1936
993   994             A11      36.0            A32     A42           3959
994   995             A14      12.0            A32     A40           2390
995   996             A14      12.0            A32     A42           1736
996   997             A11      30.0            A32     A41           3857
997   998             A14      12.0            A32     A43            804
998   999             A11      45.0            A32     A43           1845
999  1000             A12      45.0            A34     A41           4576

    savings_status employment  installment_commitment personal_status  ...   \
0              A65        A75                       4             A93  ...
1              A61        A73                       2             A92  ...
2              A61        A74                       2             A93  ...
3              A61        A74                       2             A93  ...
4              A61        A73                       3             A93  ...
5              A65        A73                       2             A93  ...
6              A63        A75                       3             A93  ...
7              A61        A73                       2             A93  ...
8              A64        A74                       2             A91  ...
9              A61        A71                       4             A94  ...
10             A61        A72                       3             A92  ...
11             A61        A72                       3             A92  ...
12             A61        A73                       1             A92  ...
13             A61        A75                       4             A93  ...
14             A61        A73                       2             A92  ...
15             A62        A73                       4             A92  ...
16             A65        A75                       4             A93  ...
17             A65        A72                       2             A93  ...
18             A61        A75                       4             A92  ...
19             A63        A75                       3             A93  ...
20             A61        A73                       4             A93  ...
21             A63        A73                       2             A93  ...
22             A61        A72                       1             A93  ...
23             A62        A72                       3             A93  ...
24             A65        A73                       2             A94  ...
25             A61        A73                       1             A93  ...
26             A61        A75                       4             A94  ...
27             A64        A73                       3             A92  ...
28             A61        A73                       3             A93  ...
29             A61        A75                       3             A93  ...
..             ...        ...                     ...             ...  ...
970            A62        A73                       4             A93  ...
971            A61        A73                       1             A93  ...
972            A61        A71                       1             A92  ...
973            A61        A75                       4             A93  ...
974            A61        A73                       4             A92  ...
975            A63        A73                       3             A92  ...
976            A61        A73                       2             A92  ...
977            A65        A75                       4             A93  ...
978            A61        A75                       4             A93  ...
979            A62        A73                       2             A94  ...
980            A61        A74                       2             A93  ...
981            A61        A71                       3             A93  ...
982            A62        A73                       1             A92  ...
983            A61        A73                       2             A93  ...
984            A61        A74                       2             A93  ...
985            A61        A73                       4             A92  ...
986            A61        A72                       2             A91  ...
987            A62        A71                       2             A92  ...
988            A61        A71                       4             A93  ...
989            A61        A75                       4             A93  ...
990            A65        A72                       2             A93  ...
991            A62        A75                       4             A93  ...
992            A65        A74                       2             A94  ...
993            A61        A71                       4             A93  ...
994            A65        A75                       4             A93  ...
995            A61        A74                       3             A92  ...
996            A61        A73                       4             A91  ...
997            A61        A75                       4             A93  ...
998            A61        A73                       4             A93  ...
999            A62        A71                       3             A93  ...

    property_magnitude  age other_payment_plans  housing existing_credits  \
0                 A121   67                A143     A152                2
1                 A121   22                A143     A152                1
2                 A121   49                A143     A152                1
3                 A122   45                A143     A153                1
4                 A124   53                A143     A153                2
5                 A124   35                A143     A153                1
6                 A122   53                A143     A152                1
7                 A123   35                A143     A151                1
8                 A121   61                A143     A152                1
9                 A123   28                A143     A152                2
10                A123   25                A143     A151                1
11                A122   24                A143     A151                1
12                A123   22                A143     A152                1
13                A123   60                A143     A152                2
14                A123   28                A143     A151                1
15                A123   32                A143     A152                1
16                A122   53                A143     A152                2
17                A123   25                A141     A152                3
18                A124   44                A143     A153                1
19                A123   31                A143     A152                1
20                A123   48                A143     A152                3
21                A121   44                A143     A151                1
22                A121   48                A143     A151                2
23                A122   44                A143     A152                1
24                A123   26                A143     A152                2
25                A121   36                A141     A152                1
26                A123   39                A143     A152                1
27                A121   42                A143     A151                2
28                A121   34                A143     A152                1
29                A124   63                A143     A152                2
..                 ...  ...                 ...      ...              ...
970               A121   22                A143     A152                1
971               A122   43                A143     A152                1
972               A124   29                A143     A151                2
973               A124   36                A143     A151                1
974               A123   33                A143     A152                1
975               A123   57                A143     A152                1
976               A121   64                A143     A152                1
977               A122   42                A143     A152                2
978               A123   47                A143     A152                2
979               A122   25                A143     A151                1
980               A122   49                A143     A152                1
981               A123   33                A141     A151                1
982               A123   28                A141     A152                1
983               A122   26                A143     A152                1
984               A122   30                A143     A152                2
985               A122   25                A143     A151                2
986               A122   33                A143     A152                2
987               A121   64                A143     A152                1
988               A124   29                A143     A153                1
989               A122   48                A143     A152                2
990               A122   37                A143     A152                2
991               A123   34                A141     A152                1
992               A123   23                A143     A151                2
993               A122   30                A143     A152                1
994               A123   50                A143     A152                1
995               A121   31                A143     A152                1
996               A122   40                A143     A152                1
997               A123   38                A143     A152                1
998               A124   23                A143     A153                1
999               A123   27                A143     A152                1

      job  num_dependents own_telephone  foreign_worker class
0    A173             1.0          A192            A201     1
1    A173             NaN          A191            A201     2
2    A172             2.0          A191            A201     1
3    A173             2.0          A191            A201     1
4    A173             2.0          A191            A201     2
5    A172             NaN          A192            A201     1
6    A173             1.0          A191            A201     1
7    A174             1.0          A192            A201     1
8    A172             1.0          A191            A201     1
9    A174             1.0          A191            A201     2
10   A173             1.0          A191            A201     2
11   A173             1.0          A191            A201     2
12   A173             NaN          A192            A201     1
13   A172             1.0          A191            A201     2
14   A173             1.0          A191            A201     1
15   A172             1.0          A191            A201     2
16   A173             NaN          A191            A201     1
17   A173             1.0          A191            A201     1
18   A174             1.0          A192            A201     2
19   A173             2.0          A192            A201     1
20   A173             1.0          A192            A201     1
21   A173             2.0          A191            A201     1
22   A172             2.0          A191            A202     1
23   A173             1.0          A191            A201     1
24   A173             1.0          A191            A202     1
25   A172             1.0          A192            A201     1
26   A172             1.0          A191            A201     1
27   A173             1.0          A191            A201     1
28   A173             1.0          A191            A201     1
29   A173             1.0          A192            A201     2
..    ...             ...           ...             ...   ...
970  A173             1.0          A191            A201     1
971  A172             2.0          A191            A201     1
972  A171             1.0          A191            A201     2
973  A173             1.0          A191            A201     2
974  A173             1.0          A192            A201     1
975  A172             1.0          A191            A201     1
976  A173             1.0          A191            A201     1
977  A173             1.0          A191            A201     1
978  A172             2.0          A191            A201     2
979  A173             1.0          A191            A201     2
980  A173             1.0          A191            A201     2
981  A174             1.0          A192            A201     2
982  A174             1.0          A192            A201     1
983  A173             2.0          A191            A201     2
984  A172             1.0          A191            A201     1
985  A173             1.0          A191            A201     1
986  A173             1.0          A191            A201     1
987  A173             1.0          A191            A201     1
988  A174             1.0          A192            A201     1
989  A172             1.0          A191            A201     1
990  A172             2.0          A191            A201     1
991  A172             2.0          A191            A201     1
992  A172             1.0          A191            A201     1
993  A174             1.0          A192            A201     1
994  A173             1.0          A192            A201     1
995  A172             1.0          A191            A201     1
996  A174             1.0          A192            A201     1
997  A173             1.0          A191            A201     1
998  A173             1.0          A192            A201     2
999  A173             1.0          A191            A201     1

[1000 rows x 22 columns]

In [4]:
def unique_count(df, label,report):
    unique_list = df[label].unique()
    unique_num = len(unique_list)
    report.ix[label]["unique_num"] = unique_num 
    

report= pd.DataFrame(index=col,columns=["unique_num"])   
for i in range(len(col)): unique_count(df,col[i],report)
print(report)

                       unique_num
ID                           1000
checking_status                 4
duration                       34
credit_history                  5
purpose                        12
credit_amount                 921
savings_status                  5
employment                      5
installment_commitment          4
personal_status                 4
other_parties                   3
residence_since                 4
property_magnitude              4
age                            53
other_payment_plans             3
housing                         3
existing_credits                4
job                             4
num_dependents                  3
own_telephone                   2
foreign_worker                  2
class                           2

c:\users\student\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:4: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  after removing the cwd from sys.path.

In [5]:
def count_null(df, label, report):
    report.ix[label,'null_num'] = df[label].isnull().sum()


for i in range(len(col)): count_null(df,col[i],report)
print(report)

                       unique_num  null_num
ID                           1000       0.0
checking_status                 4       0.0
duration                       34       4.0
credit_history                  5       0.0
purpose                        12       3.0
credit_amount                 921       0.0
savings_status                  5       0.0
employment                      5       0.0
installment_commitment          4       0.0
personal_status                 4       0.0
other_parties                   3       0.0
residence_since                 4       0.0
property_magnitude              4       0.0
age                            53       0.0
other_payment_plans             3       0.0
housing                         3       0.0
existing_credits                4       0.0
job                             4       0.0
num_dependents                  3       4.0
own_telephone                   2       0.0
foreign_worker                  2       0.0
class                           2       0.0

c:\users\student\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:2: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated

# Main

In [6]:
def count_null(df, label, report):
    unique_list = df[label].unique()
    unique_num = len(unique_list)
    report.ix[label]["unique_num"] = unique_num 
    
    report.ix[label,'null_num'] = df[label].isnull().sum()


for i in range(len(col)): count_null(df,col[i],report)
print(report)

c:\users\student\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:4: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  after removing the cwd from sys.path.
c:\users\student\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.
c:\users\student\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:6: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated

                       unique_num  null_num
ID                           1000       0.0
checking_status                 4       0.0
duration                       34       4.0
credit_history                  5       0.0
purpose                        12       3.0
credit_amount                 921       0.0
savings_status                  5       0.0
employment                      5       0.0
installment_commitment          4       0.0
personal_status                 4       0.0
other_parties                   3       0.0
residence_since                 4       0.0
property_magnitude              4       0.0
age                            53       0.0
other_payment_plans             3       0.0
housing                         3       0.0
existing_credits                4       0.0
job                             4       0.0
num_dependents                  3       4.0
own_telephone                   2       0.0
foreign_worker                  2       0.0
class                           2       0.0